volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: shaginsn/foodgram_backend
    depends_on:
      - db
    env_file: .env
    volumes:
      - static_volume:/backend_static
      - media_volume:/backend/media
  frontend:
    image: shaginsn/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: shaginsn/foodgram_gateway
    depends_on:
      - backend
    env_file: .env
    volumes:
      - static_volume:/staticfiles
      - media_volume:/media
    ports:
      - 9090:80