# Generated by Django 3.2.3 on 2025-08-23 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_short_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='short_link',
            new_name='short_hash',
        ),
    ]
