# Generated by Django 3.2.3 on 2025-09-02 13:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_rename_short_link_recipe_short_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Время готовки не может быть меньше 1 мин.'), django.core.validators.MaxValueValidator(32000, 'Время готовки не может быть больше 32000 мин.')], verbose_name='Время приготовления (минуты)'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Время готовки не может быть меньше 1'), django.core.validators.MaxValueValidator(32000, 'Время готовки не может быть больше 32000')], verbose_name='Количество'),
        ),
    ]
